### ISSUE TITLE
Performance Monitoring for v3.3 logs

### ISSUE THREAD

**Issue by bionicbone** [diydrones/APM_Log_File_Analyzer#222]
Errors occur for this type of analysis under v3.3

**Comment by bionicbone** [comment]
Test file: RoboCat 270, any log

**Comment by bionicbone** [comment]
I added this fix in as it was very quick

However, the Pixhawk Hardware has very different results in the PM line.

I have raised a WiKi issue to see if we can have more clarification.
https://github.com/diydrones/ardupilot-wiki-issue-tracker/issues/286

**Comment by bionicbone** [comment]
NLoop should be Clock frequency * 10, i.e. my APM logs 100Hz so NLoop = 1000, my Pix Logs are 400Hz so NLoop = 4000.

Key is that NLon is not more than 15% of NLoop.

Recode to have one main analysis for all versions / hardware.

Run all test logs before releasing, if results are good make analyse the Performance Monitoring by default.

**Comment by bionicbone** [comment]
Some Test code in Branch Performance_Management

**Comment by TheQuestor** [comment]
I gotta say most of what you wrote is WAY over my head lol. Some it made sense but a lot of it sounded like a magic language.

I kind of wish the devs would slow down some and stop changing so much so fast. 

 

It looks like you have a handle on things though and this tool just keeps getting better and better and I wonder why Michael hasn’t asked you to integrate this into mission planner yet!

 

Hopefully in the next week or so I can get my quad and hex out for some logging tests to see just how well the app is working J

**Comment by bionicbone** [comment]
I have created a Wiki Page to describe how this works, no point in making a long comment here.

https://github.com/diydrones/APM_Log_File_Analyzer/wiki/5.Performance-Analysis

[PM Testing.xlsx](https://github.com/diydrones/APM_Log_File_Analyzer/files/127681/PM.Testing.xlsx)

The GCS and I2C errors are still part of the PM checks but are performed as default now even though the "Perf Mon Additional Information" check box is unchecked as default.
