### ISSUE TITLE
Line counts

### ISSUE THREAD

**Issue by bionicbone** [diydrones/APM_Log_File_Analyzer#224]
Are the displayed line counts all +1?

They are correct in the Debug Analysis as I use that all the time :)

Reported by Robin (rsilk on RCGroups)

**Comment by bionicbone** [comment]
Hi Robin,

I disagree, unless you can show me otherwise?

![image](https://cloud.githubusercontent.com/assets/7845867/13000740/01989332-d156-11e5-9308-861a2a31dda5.png)

**Comment by bionicbone** [comment]
I'm going to close this issue, please reopen if you can provide more information on this topic.
Thanks
Kev

**Comment by rsilk1949** [comment]
Notepad and Mission planner show difference of 1. Likely a bug in MP (Kev to raise issue).
